{% set version = "7.1" %}
{% set name = "pyobjc-framework-Cocoa" %}

package:
  name: pyobjc-framework-cocoa
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 67966152b3d38a0225176fceca2e9f56d849c8e7445548da09a00cb13155ec3e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [(not osx) or py2k]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - pyobjc-core >=7.1

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - AppKit
    - Cocoa
    - CoreFoundation
    - Foundation
    - PyObjCTools

about:
  home: https://bitbucket.org/ronaldoussoren/pyobjc
  license: MIT
  license_file: LICENSE.txt
  summary: Wrappers for the Cocoa frameworks on Mac OS X

extra:
  recipe-maintainers:
    - jschueller
