{% set version = "7.2" %}
{% set name = "pyobjc-framework-Cocoa" %}

package:
  name: pyobjc-framework-cocoa
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c8b23f03dc3f4436d36c0fd006a8a084835c4f6015187df7c3aa5de8ecd5c653

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [(not osx) or py2k or python_impl == 'pypy']

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - pyobjc-core >=7.1

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - AppKit
    - Cocoa
    - CoreFoundation
    - Foundation
    - PyObjCTools

about:
  home: https://bitbucket.org/ronaldoussoren/pyobjc
  license: MIT
  license_file: LICENSE.txt
  summary: Wrappers for the Cocoa frameworks on Mac OS X

extra:
  recipe-maintainers:
    - leofang
    - jschueller
